### ISSUE TITLE
Visa progress bar med %

### ISSUE THREAD

**Issue by dlidstrom** [dlidstrom/MinaGlosor#56]
Använd en style som den här:

```css
.progress.progress-flat {
  margin-bottom: 0;
  position: relative;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#FFDFDFDF',endColorstr='#FFCFCFCF',GradientType=0);
  background-color: #fdfdfd;
  background-image: -moz-linear-gradient(top,#fdfdfd,#cfcfcf);
  background-image: -webkit-gradient(linear,0 0,0 100%,from(#fdfdfd),to(#cfcfcf));
  background-image: -webkit-linear-gradient(top,#fdfdfd,#cfcfcf);
  background-image: -o-linear-gradient(top,#fdfdfd,#cfcfcf);
  background-image: linear-gradient(to bottom,#fdfdfd,#cfcfcf);
}
.progress span.progress-label {
  position: absolute;
  left: 4px;
  font-weight: bold;
  color: #fff;
  text-shadow: 0 1px 1px rgba(0,0,0,.7);
}
```

Markup så här:
```html
<div class="progress progress-flat">
  <div class="bar bar-success" style="width: 100%"></div>
  <div class="bar bar-danger" style="width: 0%"></div>
  <span class="progress-label">100%</span>
</div>
```
